import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from './../components/Banner'
import Image from 'next/image'
import Card from '../components/Card';
import data from '../data/coffee-stores.json'
// import {fetchStores}  from '../lib/stores'
// import { useState } from 'react'
// const inter = Inter({ subsets: ['latin'] })
import Navbar from '../components/Navbar'


export async function getStaticProps(){
  const stores = data // await fetchStores();
  return{
    props:{
      coffeeStores : stores ,
    }
  }
}
const Home=(props: any)=> {

  // const [authenticated, setAuthenticated] = useState(false);

  // console.log("props:", props)
  // const userData = window.localStorage.getItem("user-data");
  // const isAuthenticated = localStorage.getItem("isAuthenticated");

  const handleOnViewButtonClick=()=>{
      console.log("View button is Clicked");
  }

  return (
    <>
      <Navbar/>

      <Head>
        <title>Find Stores Nearby</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner 
          buttonTitle="Find Shops Nearby" 
          handleOnClick={handleOnViewButtonClick}
          className={styles.homeBanner}
        />
        <div className={styles.heroImage}>
        <Image  src="/static/hero-image.png" width={700} height={400} alt='' />
       
        </div>
         {props.coffeeStores.length > 0 && <div>
          <h2 className={styles.heading2}>Toronto Stores</h2>
          <div className={styles.cardLayout}>
          {props.coffeeStores.map((coffeeStore:any)=>{
            return(
              <Card cardName={coffeeStore.name} imgUrl={coffeeStore.imgUrl} href={`/coffee-store/${coffeeStore.id}`} key={coffeeStore.id}/>
            )
          })}
        </div>
          </div>}
        
      </main>
    </>
  )
}

export default Home;
